# Generated by Django 5.2.7 on 2025-10-31 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.employerprofile"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.employerprofile"
            ),
        ),
        migrations.AddField(
            model_name="skillassessment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.studentprofile"
            ),
        ),
    ]
